openapi: 3.0.0
info:
  title: Auth Service
  version: 1.0.0
  description: API endpoints for authentication (sign up, login, logout, refresh token)

paths:
  /auth/signup:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, userTag, email, password]
              properties:
                username:
                  type: string
                userTag:
                  type: string
                email:
                  type: string
                password:
                  type: string

      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  metadata:
                    type: string

  /auth/login:
    post:
      summary: Login user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  metadata:
                    type: object
                    properties:
                      accessToken:
                        type: string

  /auth/logout:
    get:
      summary: Logout user
      tags: [Auth]
      responses:
        '204':
          description: Logged out successfully

  /auth/get-new-access-token:
    get:
      summary: Refresh access token
      tags: [Auth]
      responses:
        '200':
          description: Provide access token successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  metadata:
                    type: string
